---
- hosts: soulprovidr.fm
  remote_user: "{{ ssh_user }}"
  become: yes
  become_method: sudo

  vars:
    bucket_name: soulprovidr.fm
    domains:
      - soulprovidr.fm
      - www.soulprovidr.fm
    email: shola@soulprovidr.co
    home_path: /home/{{ ssh_user }}
    media_folder: media
    repository: https://github.com/soulprovidr/soulprovidr.fm
    ssh_user: soulprovidr
    stream_name: stream.mp3
    web_dir: "/home/{{ ssh_user }}/{{ domains | first }}/src/app"
    web_root: "{{ web_dir }}/public"

  roles:
    - { role: 'nginx', tags: ['nginx'] }
    - { role: 'redis', tags: ['redis'] }
    - { role: 'storage', tags: ['storage'] }
    - { role: 'stream', tags: ['stream'] }
    - { role: 'website', tags: ['website'] }