---
- hosts: soulprovidr.fm
  remote_user: soulprovidr
  become: yes
  become_method: sudo

  vars:
    bucket_name: soulprovidr.fm
    domains:
      - soulprovidr.fm
      - www.soulprovidr.fm
    email: shola@soulprovidr.co
    repository: https://github.com/soulprovidr/soulprovidr.fm
    user: soulprovidr
    web_dir: "/home/{{ user }}/{{ domains | first }}"
    web_root: "{{ web_dir }}/public"

  roles:
    - { role: 'icecast', tags: ['icecast'] }
    - { role: 'webserver', tags: ['webserver'] }
    - { role: 'website', tags: ['website'] }
    - { role: 'storage', tags: ['storage'] }