---
- hosts: soulprovidr.fm
  remote_user: "{{ project.user }}"
  become: yes
  become_method: sudo

  vars:
    project:
      email: shola@soulprovidr.co
      path: "{{ lookup('env', 'HOME') }}/soulprovidr.fm"
      repository: https://github.com/soulprovidr/soulprovidr.fm
      user: soulprovidr
    api:
      path: "{{ project.path }}/src/api"
    app:
      path: "{{ project.path }}/src/app"
    nginx:
      domains:
        - soulprovidr.fm
        - www.soulprovidr.fm
      root: "{{ project.path }}/public"
    storage:
      bucket: soulprovidr.fm
      path: "{{ lookup('env', 'HOME') }}/media"
    stream:
      notify: node {{ api.path }}/notify

  roles:
    - { role: 'app', tags: ['app'] }
    - { role: 'nginx', tags: ['nginx'] }
    - { role: 'redis', tags: ['redis'] }
    - { role: 'storage', tags: ['storage'] }
    - { role: 'stream', tags: ['stream'] }