---
- name: Install pm2
  tags: ['never']
  become: true
  shell: yarn global add pm2

# - name: Delete pm2 jobs
#   tags: ['never']
#   shell: pm2 delete all 2>/dev/null

- name: Start api process
  tags: ['never']
  shell: pm2 start {{ api.path }}/main.js