---
- name: Install OPAM
  tags: ['never']
  apt:
    name: opam
    state: present

- name: Install liquidsoap
  tags: ['never']
  become_user: "{{ project.user }}"
  shell: "opam init -y && opam install {{ stream.liquidsoap.dependencies | join(' ') }}"

- name: Copy stream config
  tags: ['never']
  template:
    src: templates/main.liq
    dest: "{{ stream.liquidsoap.paths.script }}"

# TODO: Add loop
- name: Create log file
  tags: ['never']
  file:
    path: "{{ stream.liquidsoap.paths.log }}"
    owner: "{{ project.user }}"
    group: "{{ project.user }}"
    state: touch

- name: Create pid file
  tags: ['never']
  file:
    path: "{{ stream.liquidsoap.paths.pid }}"
    owner: "{{ project.user }}"
    group: "{{ project.user }}"
    state: touch

- name: Generate stream
  tags: ['never']
  become_user: "{{ project.user }}"
  shell: "eval $(opam config env) liquidsoap --daemon {{ stream.liquidsoap.paths.script }}"