---
- name: Clone website repository
  tags: ['never']
  git:
    repo: "{{ repository }}"
    dest: "{{ web_dir }}"

- name: Install website dependencies
  tags: ['never']
  yarn:
    path: "{{ web_dir }}"
    state: latest

- name: Build website
  tags: ['never']
  shell: yarn build
  args:
    chdir: "{{ web_dir }}"