---
- name: Install s3fs
  tags: ['never']
  apt:
    name: s3fs
    state: present

- include_vars: credentials.yml

- name: Create password file
  tags: ['never']
  become_user: "{{ project.user }}"
  template:
    src: templates/passwd-s3fs
    dest: "{{ lookup('env', 'HOME') }}/.passwd-s3fs"
    mode: 0600

- name: Unmount directory
  tags: ['never']
  shell: "umount {{ storage.path }} || :"

- name: Remove directory
  tags: ['never']
  file:
    path: "{{ storage.path }}"
    state: absent

- name: Create mount directory
  tags: ['never']
  become_user: "{{ project.user }}"
  file:
    path: "{{ storage.path }}"
    state: directory
    mode: 0755

- name: Mount S3 bucket
  tags: ['never']
  become_user: "{{ project.user }}"
  shell: "s3fs {{ storage.bucket }} {{ storage.path }} -o passwd_file={{ lookup('env', 'HOME') }}/.passwd-s3fs -o umask=0022"
