---
- name: Install dependencies
  tags: [ 'never' ]
  apt:
    name: software-properties-common
    state: present

- name: Add certbot repository
  tags: [ 'never' ]
  apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Install certbot
  tags: [ 'never' ]
  apt:
    name: certbot
    state: present

- name: Check for SSL certificate
  tags: [ 'never' ]
  stat:
    path: "/etc/letsencrypt/live/{{ domains | first }}/cert.pem"
  register: letsencrypt_cert

- name: Stop nginx
  tags: [ 'never' ]
  when: not letsencrypt_cert.stat.exists
  systemd:
    name: nginx
    state: stopped

- name: Generate SSL certificate
  tags: [ 'never' ]
  when: not letsencrypt_cert.stat.exists
  shell: "certbot certonly --standalone --noninteractive --agree-tos --email {{ email }} -d {{ domains | join(',') }}"

- name: Add cron job for SSL certificate renewal
  tags: [ 'never' ]
  when: not letsencrypt_cert.stat.exists
  cron:
    name: renew ssl
    job: "certbot renew --quiet --no-self-upgrade"
    minute: 30
    hour: 3
    user: "{{ ansible_user }}"